# Generated by Django 6.0.4 on 2026-04-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bootstrap_icon_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
