# Generated by Django 6.0.4 on 2026-04-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_bootstrap_icon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='bootstrap_icon_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
