# Generated by Django 6.0.4 on 2026-04-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User Profiles'},
        ),
    ]
